{
 "title": "FIAP Dashboard Aplicação",
 "description": "Monitorar se a aplicação está performando bem e respondendo corretamente",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(api_requests_total,endpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS por endpoint",
   "type": "timeseries",
   "description": "{{endpoint}}",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (api_requests_total{endpoint=~\"$endpoint\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de requisições por endpoint",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_requests_total{endpoint=\"$endpoint\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência das requisições",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(api_request_duration_seconds_sum[10m])\r\n\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de sucesso (200/201)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (http_route) (rate(microsoft_aspnetcore_hosting_http_server_request_duration_count{http_response_status_code=~\"200|201\", http_route=~\"$endpoint\"}[10m]))\r\n)\r\n/\r\n(\r\n  sum by (http_route) (rate(microsoft_aspnetcore_hosting_http_server_request_duration_count{http_route=~\"$endpoint\"}[10m]))\r\n)\r\n* 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de erro (400/500)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "(\r\n  sum by (http_route) (rate(microsoft_aspnetcore_hosting_http_server_request_duration_count{http_response_status_code=~\"400|404|500\", http_route=~\"$endpoint\"}[10m]))\r\n)\r\n/\r\n(\r\n  sum by (http_route) (rate(microsoft_aspnetcore_hosting_http_server_request_duration_count{http_route=~\"$endpoint\"}[10m]))\r\n)\r\n* 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tamanho do Heap .NET GC",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_runtime_gc_heap_size / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de alocação de memória",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(system_runtime_alloc_total[5m]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads do ThreadPool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "dotnet_threadpool_num_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uso de CPU da aplicação",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[10m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de memória RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "process_working_set_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}